package unique

import (
	"github.com/stretchr/testify/require"
	"testing"
)

var tests = []struct {
	str     []string
	options Options
	res     []string
}{
	{[]string{"I love music.",
		"I love music.",
		"I love music.",
		"",
		"I love music of Kartik.",
		"I love music of Kartik.",
		"Thanks.",
		"I love music of Kartik.",
		"I love music of Kartik."},
		Options{
			Count:      false,
			Duplicate:  false,
			Unique:     false,
			SkipFields: 0,
			SkipChars:  0,
			Ignore:     false,
		},
		[]string{"I love music.",
			"",
			"I love music of Kartik.",
			"Thanks.",
			"I love music of Kartik."}},

	{[]string{"I love music.",
		"I love music.",
		"I love music.",
		"",
		"I love music of Kartik.",
		"I love music of Kartik.",
		"Thanks.",
		"I love music of Kartik.",
		"I love music of Kartik."},
		Options{
			Count:      true,
			Duplicate:  false,
			Unique:     false,
			SkipFields: 0,
			SkipChars:  0,
			Ignore:     false,
		},
		[]string{"3 I love music.",
			"1 ",
			"2 I love music of Kartik.",
			"1 Thanks.",
			"2 I love music of Kartik."}},

	{[]string{"I love music.",
		"I love music.",
		"I love music.",
		"",
		"I love music of Kartik.",
		"I love music of Kartik.",
		"Thanks.",
		"I love music of Kartik.",
		"I love music of Kartik."},
		Options{
			Count:      false,
			Duplicate:  true,
			Unique:     false,
			SkipFields: 0,
			SkipChars:  0,
			Ignore:     false,
		},
		[]string{"I love music.",
			"I love music of Kartik.",
			"I love music of Kartik."}},

	{[]string{"I love music.",
		"I love music.",
		"I love music.",
		"",
		"I love music of Kartik.",
		"I love music of Kartik.",
		"Thanks.",
		"I love music of Kartik.",
		"I love music of Kartik."},
		Options{
			Count:      false,
			Duplicate:  false,
			Unique:     true,
			SkipFields: 0,
			SkipChars:  0,
			Ignore:     false,
		},
		[]string{"",
			"Thanks."}},

	{[]string{"I LOVE MUSIC.",
		"I love music.",
		"I LoVe MuSiC.",
		"",
		"I love MuSIC of Kartik.",
		"I love music of kartik.",
		"Thanks.",
		"I love music of kartik.",
		"I love MuSIC of Kartik."},
		Options{
			Count:      false,
			Duplicate:  false,
			Unique:     false,
			SkipFields: 0,
			SkipChars:  0,
			Ignore:     true,
		},
		[]string{"I LOVE MUSIC.",
			"",
			"I love MuSIC of Kartik.",
			"Thanks.",
			"I love music of kartik."}},

	{[]string{"We love music.",
		"I love music.",
		"They love music.",
		"",
		"I love music of Kartik.",
		"We love music of Kartik.",
		"Thanks."},
		Options{
			Count:      false,
			Duplicate:  false,
			Unique:     false,
			SkipFields: 1,
			SkipChars:  0,
			Ignore:     false,
		},
		[]string{"We love music.",
			"",
			"I love music of Kartik.",
			"Thanks."}},

	{[]string{"I love music.",
		"A love music.",
		"I love music.",
		"C love music.",
		"",
		"I love music of Kartik.",
		"We love music of Kartik.",
		"Thanks."},
		Options{
			Count:      false,
			Duplicate:  false,
			Unique:     false,
			SkipFields: 0,
			SkipChars:  1,
			Ignore:     false,
		},
		[]string{"I love music.",
			"",
			"I love music of Kartik.",
			"We love music of Kartik.",
			"Thanks."}},
}

func TestUniqueCorrect(t *testing.T) {
	for _, e := range tests {
		require.Equal(t, e.res, Unique(e.str, e.options), "Check Unique func")
	}
}
